### ISSUE TITLE
Car Price Prediction Model

### ISSUE THREAD

**Issue by jainriya9** [Soumya-Kushwaha/ML-Fest#13]
Car Price Prediction ML Model using Linear Regression, Decision Tree and Random Forest

**Comment by Soumya-Kushwaha** [comment]
Add a little description on new issues always, Riya. Like the dataset or the algos you plan to use, can be anything. 

All the best for this one! 🙌

**Comment by jainriya9** [comment]
> Add a little description on new issues always, Riya. Like the dataset or the algos you plan to use, can be anything.
> 
> All the best for this one! 🙌

Is the Readme of the Model required?
@Soumya-Kushwaha

**Comment by Soumya-Kushwaha** [comment]
Yeah, even a brief one will do.

**Comment by jainriya9** [comment]
> Yeah, even a brief one will do.

Okay!
