### ISSUE TITLE
ML Projects for Hacktoberfest!

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/ML-Fest#2]
Add machine learning projects and kickstart your Hacktoberfest !!

**Comment by kittoteja** [comment]
assigne me

**Comment by Soumya-Kushwaha** [comment]
@kittoteja Please create a new issue about the project you want to add

**Comment by Soumya-Kushwaha** [comment]
@kittoteja done. please go ahead!

**Comment by kittoteja** [comment]
please create another folder

**Comment by Soumya-Kushwaha** [comment]
For the project you're interested in, create a new folder, and add Readme & project inside the folder.

**Comment by kittoteja** [comment]
I have to create two pull request

**Comment by kittoteja** [comment]
so first create a folder in main where I can place the project

**Comment by Soumya-Kushwaha** [comment]
Place your project folder in main 😅

**Comment by kittoteja** [comment]
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Yoga_pose-ml/

nothing added to commit but untracked files present (use "git add" to track)

**Comment by kittoteja** [comment]
I am unable to add

**Comment by Soumya-Kushwaha** [comment]
It's okay. I'll help you out.
When you open the fork of this repo, do the following:
-> "Add file"
-> "Upload file"
-> Drag the folder you want to upload to the area - it will automatically upload all the files
-> Commit the changes & generate PR.

Hope this helps!

**Comment by Soumya-Kushwaha** [comment]
@kittoteja updates?

**Comment by jainriya9** [comment]
Greetings!

I can make a Car Price Prediction Model based on numerous attributes like Car Height, Engine Size and many more to predict the price of car. Looking forward to contribute!

Thankyou!
@Soumya-Kushwaha

**Comment by PrasannaBG** [comment]
I can make a Plant Disease classification model using Transfer Learning

I like to contribute to this issue. Assign me this issue.

**Comment by Soumya-Kushwaha** [comment]
@PrasannaBG & @jainriya9 please create individual issues. And I'll be happy to assign! :)

**Comment by jainriya9** [comment]
> @PrasannaBG & @jainriya9 please create individual issues. And I'll be happy to assign! :)

Created @Soumya-Kushwaha 
Thanks!
