### ISSUE TITLE
Setup issue templates

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/ML-Fest#7]
Setup issue templates for 2 issues:
-> New project addition
-> Documentation based issues

**Comment by Pariharx7** [comment]
I wanted to work on this issue. 

Can you assign me the issue.

**Comment by Soumya-Kushwaha** [comment]
Definitely @Pariharx7 . You're good to go!

**Comment by Pariharx7** [comment]
Should I make templates.md and send PR regarding them

**Comment by Soumya-Kushwaha** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
This should help.

**Comment by Pariharx7** [comment]
Thanks for resources, already forked the repo, made a new branch and also enabled the Issue feature, but didn't refreshed the page , that's why was stucked. 

Will get the work done by tomorrow.

**Comment by Soumya-Kushwaha** [comment]
Sure. All the best.

**Comment by Pariharx7** [comment]
I created a PR based on the first method that was mentioned in the documentation, please review it. 

Also if it's not good, I'll try to the work with the Creating Issue Forms method

**Comment by Soumya-Kushwaha** [comment]
I believe it works!

**Comment by Soumya-Kushwaha** [comment]
But we need 1 more - for new project addition. Call it "New Project", maybe?

**Comment by Pariharx7** [comment]
Sure, should I follow the same procedure for this one or try to do that with Issue forms using yaml

**Comment by Soumya-Kushwaha** [comment]
Same procedure. It'll be consistent.

**Comment by Pariharx7** [comment]
By Project Addition, you mean like an issue where user wants a new Feature 🤔
